### ISSUE TITLE
World shutdown after attempting to break blocks

### ISSUE THREAD

**Issue by ChatFawkes** [Elecs-Mods/GregsProspecting-II#2]
https://gist.github.com/ChatFawkes/c04402e2b24b71e21549

This happens when trying to break a block in the world. After that it shuts down and tells me a fatal error has occurred, but doesn't crash the client to desktop (it just brings me back to the main menu). I can seem to explore and toss items, but as soon as I attempt to break a block I get kicked to the main menu.

**Comment by Elec332** [comment]
Break a block with the prospect item, or just any item?
