### ISSUE TITLE
Crash on Changing Prospector Mode

### ISSUE THREAD

**Issue by BearInABox** [Elecs-Mods/GregsProspecting-II#3]
http://pastebin.com/4iZSikE2

Above is a link to pastebin where I have uploaded a crash report that occurs when I press [, ], L, or M to change the range or mode of the prospector (both normal and colored).  

The environment should be clean of other mods; I made a new launcher profile with a new directory with just this mod, ElecCore, and forge 1291 in 1.7.10.  I also replicated the crash with forge 1230 in 1.7.10.

That's all the information I can think of that might be relevant, sorry to be so brief.  Thank you for your time.

**Comment by Elec332** [comment]
Thats strange, because I cannot reproduce this.
Ill look into it.

**Comment by BearInABox** [comment]
Hmm yeah, that is strange.  Could you maybe give me a little insight into what it's trying to do and what exactly it's failing at so I could look for possible stumbling blocks in my own hardware or things like Java?  I just tried it on a laptop (on my same local network though) with a brand new install of MC and it still occurred.  The log doesn't appear to mention in its little synopsis of my system specs that I'm running a 64 bit environment; I can come up with a full list of system and network specs if you need them.  That's really strange.

**Comment by Elec332** [comment]
The crashlog basically says that this: https://github.com/Elecs-Mods/ElecCore/blob/master/src/main/java/elec332/core/network/AbstractPacket.java#L32

Doesnt exist...

**Comment by BearInABox** [comment]
I found a thing.  The crash only occurs with ElecCore 1.3.65, the version I quickly snapped off of Curse.  1.3.62 works beautifully for everything.  The changelog for .65 mentions some network overhauling, which I might assume is related to the networkPackageObject that it's whining about in the crash.  I'm definitely not a programmer though.  I'm really sorry, this issue is kind of me not reading what the recommended version was and downloading what appears now to be the very latest build.  I hope I didn't make you too frustrated by being dumb; thank you for your time.

**Comment by Elec332** [comment]
Ill look into it again tomorrow ;)
(I think I know whats wrong)
